// biome-ignore lint/performance/noBarrelFile: this facade intentionally preserves the public config module contract.
export { parseArgs } from "./config/args.ts";
export {
  advisorAutoLoopGateRef,
  advisorBlockOnBlockedRef,
  advisorCollapseResponsesRef,
  advisorCompletionGateRef,
  advisorCustomInvocationRef,
  advisorEffortRef,
  advisorFailureGateRef,
  advisorFailureModeRef,
  advisorGitContextMaxCharsRef,
  advisorGitContextRef,
  advisorHerdrIntegrationRef,
  advisorLoopThresholdRef,
  advisorMaxCallsPerSessionRef,
  advisorOutcomeLoggingRef,
  advisorPlanGateRef,
  advisorRedactSecretsRef,
  advisorRef,
  advisorScoutEnabledRef,
  advisorSessionSummaryRef,
  advisorToolPoliciesRef,
  advisorToolResultMaxBytesRef,
  advisorToolResultMaxLinesRef,
  advisorTrackedFileContentRef,
  advisorUntrackedContentRef,
  alwaysOnRef,
  contextMaxCharsRef,
  executorEffortRef,
  executorRef,
  getAdvisorMaxCallsPerSession,
  getAdvisorSettings,
  getPersistedModelRefs,
  isSimpleMode,
  setAdvisorAutoLoopGateRef,
  setAdvisorBlockOnBlockedRef,
  setAdvisorCollapseResponsesRef,
  setAdvisorCompletionGateRef,
  setAdvisorCustomInvocationRef,
  setAdvisorEffortRef,
  setAdvisorFailureGateRef,
  setAdvisorFailureModeRef,
  setAdvisorGitContextMaxCharsRef,
  setAdvisorGitContextRef,
  setAdvisorHerdrIntegrationRef,
  setAdvisorLoopThresholdRef,
  setAdvisorMaxCallsPerSessionRef,
  setAdvisorOutcomeLoggingRef,
  setAdvisorPlanGateRef,
  setAdvisorRedactSecretsRef,
  setAdvisorRef,
  setAdvisorScoutEnabledRef,
  setAdvisorSessionSummaryRef,
  setAdvisorToolPoliciesRef,
  setAdvisorToolResultMaxBytesRef,
  setAdvisorToolResultMaxLinesRef,
  setAdvisorTrackedFileContentRef,
  setAdvisorUntrackedContentRef,
  setAlwaysOnRef,
  setContextMaxCharsRef,
  setExecutorEffortRef,
  setExecutorRef,
  setShowUsageDetailsRef,
  setShowUsageFooterRef,
  setSimpleModeRef,
  showUsageDetailsRef,
  showUsageFooterRef,
  simpleModeRef,
  splitRef,
} from "./config/state.ts";
export type { SaveConfigOptions } from "./config/storage.ts";
export {
  configPaths,
  loadConfig,
  resetConfigCache,
  saveConfig,
  saveGlobalOutcomeLogging,
} from "./config/storage.ts";
export type {
  AdvisorConfig,
  AdvisorToolPolicies,
  AdvisorToolPolicy,
  GateFailureMode,
} from "./config/types.ts";
export {
  ADVISOR_TOOL_POLICIES,
  DEFAULT_ADVISOR_GIT_CONTEXT_MAX_CHARS,
  DEFAULT_ADVISOR_TOOL_RESULT_MAX_BYTES,
  DEFAULT_ADVISOR_TOOL_RESULT_MAX_LINES,
  DEFAULT_CONTEXT_MAX_CHARS,
  GATE_FAILURE_MODES,
  MAX_CONTEXT_MAX_CHARS,
} from "./config/types.ts";
export {
  isValidAdvisorToolPolicies,
  isValidContextMaxChars,
  isValidGateFailureMode,
  isValidLoopThreshold,
  isValidMaxCallsPerSession,
  isValidToolResultMaxBytes,
  isValidToolResultMaxLines,
  validateConfig,
} from "./config/validation.ts";
